title: This is a Test Blog
author: Mauricio Torres @Asthamor  
email: mauricio.torres.osorio@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site will host my personal developer resume and blog once it's done

# social links
twitter_username: Asthamor
github_username:  Asthamor

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
